### ISSUE TITLE
Error: While trying to resolve module `redux-dynamic-reducer`

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [ioof-holdings/redux-dynamic-reducer#18]
Hi
I'm experiencing problems bundling my react-native app after I installed `redux-dynamic-reducer` and `react-redux-dynamic-reducer`. 

I ran `npm install redux-dynamic-reducer`and `npm install react-redux-dynamic-reducer`, replaced 
the use of `import { createStore } from 'redux'` with `import { createStore } from 'redux-dynamic-reducer'` and restarted the bundler. And then the bundler throws up:

"error: bundling failed: Error: While trying to resolve module `redux-dynamic-reducer` from file `/mobile/app/redux/store.js`, the package `/mobile/node_modules/redux-dynamic-reducer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/mobile/node_modules/redux-dynamic-reducer/lib/index.js`. Indeed, none of these files exist:

  * `/mobile/node_modules/redux-dynamic-reducer/lib/index.js(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/mobile/node_modules/redux-dynamic-reducer/lib/index.js/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`"

**Notes:**
"react-native": "0.55.4",
"redux-dynamic-reducer": "git+https://github.com/Journlas/redux-dynamic-reducer.git#1.0.0", (I created a [pull request](https://github.com/ioof-holdings/redux-dynamic-reducer/pull/17) to fix [this](https://github.com/ioof-holdings/redux-dynamic-reducer/issues/5))
"react-redux-dynamic-reducer": "2.0.2",

I hope someone can help as this library looks really interesting!

Let me know if you need any additional information.

**Comment by mpeyper** [comment]
Something looks wrong with how your bundler is trying to resolve the main file.  If I'm reading it correctly, it's looking for `/mobile/node_modules/redux-dynamic-reducer/lib/index.js` or `/mobile/node_modules/redux-dynamic-reducer/lib/index.js/index` with one of the extensions `(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`.

The file `/mobile/node_modules/redux-dynamic-reducer/lib/index.js` should exist, but there is no additional extension.

Which bundler are you using?  Is there somehow in it's configuration to allow it to change the resolution to be `/mobile/node_modules/redux-dynamic-reducer/lib/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`?

As a side note, this library is not being actively developed at the moment (just bug fixes), as we have a new library that is more extendible and supports more of the redux ecosystem.  It's called [`redux-dynostore`](https://github.com/ioof-holdings/redux-dynostore).
