### ISSUE TITLE
Migration to redux v4.0.0

### ISSUE THREAD

**Issue by psamusev** [ioof-holdings/redux-dynamic-reducer#20]
Since redux officially released its major version, probably it's a good time to update packages to support it as well

**Comment by jpeyper** [comment]
Hi psamusev

This library is deprecated and likely won't be getting an update by us (although PRs will be reviewed and likely accepted).

Good news though, we have another open source library called [redux-dynostore](https://github.com/ioof-holdings/redux-dynostore) that replaces this one, and will be getting the update soon.

**Comment by psamusev** [comment]
@jpeyper thank you for updates!
