### ISSUE TITLE
support for <ParentSpaceProvider>

### ISSUE THREAD

**Issue by dhirajataws** [ioof-holdings/redux-dynamic-reducer#22]
it may be a feature request.
Can we add the feature to execute actions in a sub spaced component created by withReducer to execute in parent store scope. Basically , support <ParentSpaceProvider> or parentSpaced using an option with withReducer.

**Comment by mpeyper** [comment]
[`redux-dynamic-reducer` is deprecated](https://github.com/ioof-holdings/redux-dynamic-reducer#deprecated) so we won't be adding new features here.

This is a good suggestion for [`redux-dynostore`](https://github.com/ioof-holdings/redux-dynostore) (the replacment) though.  Feel free to raise an issue over there.

**Comment by dhirajataws** [comment]
Thanks mpeyper.
