### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by hebbian** [ioof-holdings/redux-dynamic-reducer#5]
I tried to use this library, in the first run it shows error like this:

`ERROR in ./node_modules/redux-dynamic-reducer/lib/index.js  
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/hebbian/Developments/reactjs/react-skeleton/node_modules/redux-dynamic-reducer"`

What is really happening?
Thanks.

**Comment by mpeyper** [comment]
Hi @hebbian,

We saw the same [issue in redux-subspace about a month ago](https://github.com/ioof-holdings/redux-subspace/issues/69#issuecomment-360409248).

Basically, we are including the `.babelrc` file in our npm package and you are not excluding `node_modules` from the babel process.

What can be done:
1. submit a [PR ignoring `.babelrc`](https://github.com/ioof-holdings/redux-subspace/pull/70)
2. [exclude `node_modules`](https://github.com/babel/babel-loader#usage) (assuming webpack)
3. [install babel-preset-env](https://www.npmjs.com/package/babel-preset-env)
4. wait for someone else to do 1. (probably me when I have time)
